name: timesabai
description: "App TimeSabai"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1
  getwidget: ^4.0.0
  intl: ^0.19.0
  flutter_spinkit: ^5.2.1
  shared_preferences: ^2.3.2
  google_maps_flutter: ^2.9.0
  dio: ^5.7.0
  flutter_svg: ^2.0.10+1
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  ionicons: ^0.2.2
  image_picker: ^1.1.2
  slide_to_act: ^2.0.2
  firebase_auth: ^5.3.1
  simple_month_year_picker: ^1.0.5
  geocoding: ^3.0.0
  location: ^6.0.2
  geolocator: ^10.0.0
  firebase_storage: ^12.3.2
  flutter_map: ^7.0.2
  url_launcher: ^6.3.1
  fluttertoast: ^8.2.12
  flutter_launcher_icons: ^0.10.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  file_picker: ^8.1.2
  lottie: ^3.2.0
  status_alert: ^1.0.1
  loading_animation_widget: ^1.3.0
  carousel_slider: ^5.0.0
  logger: ^2.5.0
  video_player: ^2.6.0
  flutter_staggered_grid_view: ^0.6.2
  cron: ^0.6.1
  awesome_notifications: ^0.10.0
  rive: ^0.13.20
  weather: ^3.2.1
  flutter_animate: ^4.5.2
  widgets_easier: ^0.0.10


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/play_store.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/play_store.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/rives/
    - assets/svg/
    - assets/svg/animation.json
    - assets/icons/play_store.png
